name: streamlit_mock

services:
  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin123456
      - MYSQL_DATABASE=stock_data
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.42-bookworm
    environment:
      MYSQL_ROOT_PASSWORD: admin123456
      MYSQL_DATABASE: stock_data
    volumes:
      - mysql_data:/var/lib/mysql
